# Generated by Django 5.1.4 on 2024-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Job Seeker', 'Job Seeker')], default='Job Seeker', max_length=20),
        ),
    ]
