# Generated by Django 5.1.4 on 2024-12-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='github',
            new_name='github_url',
        ),
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='linkedin',
            new_name='linkedin_url',
        ),
        migrations.RenameField(
            model_name='portfoliolink',
            old_name='other',
            new_name='other_url',
        ),
    ]
