# Generated by Django 5.1.4 on 2024-12-23 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDocumentsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='Test/resume/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
